### ISSUE TITLE
Windows 10+ x64: Native notifications that have been cleared come back when a new notification arrives

### ISSUE THREAD

**Issue by jdrch** [OrangeDrangon/android-messages-desktop#362]
**Describe the bug**
On Windows 10+ (read: 10 & 11) x64, native notifications that have been cleared return when a new notification is received in the same session

**To Reproduce**
1. Run Android Message for Desktop on Windows 10 x64
2. Receive a message, which triggers a native Windows notification
3. Clear the notification
4. Receive a subsequent message that triggers another native Windows notification

**Expected behavior**
Only the new notification generated in 4) above should whos

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10+ x64

**Additional context**

**Comment by jdrch** [comment]
# UPDATE

Signal Desktop seems to have this issue too, so it may be a problem that lives upstream in Electron(?) Any ideas?

**Comment by OrangeDrangon** [comment]
This is probably related to the other windows notification problems we are having. I honestly have no idea what is wrong and it may very well be electrons fault.

**Comment by jdrch** [comment]
> This is probably related to the other windows notification problems we are having. I honestly have no idea what is wrong and it may very well be electrons fault.

I definitely think it's an Electron problem. Does anyone know where the Electron repo/issue reporting forum is?

**Comment by OrangeDrangon** [comment]
Electron has a GitHub page.

**Comment by OrangeDrangon** [comment]
Is this resolved with our latest fix for notifications.

**Comment by jdrch** [comment]
It's not completely fixed for me but it's gotten better, with fewer previously dismissed notifications surfacing. I think part of the problem is on the Windows side of things too, but I'm not sure.

**Comment by OrangeDrangon** [comment]
Has the new update helped at all?

**Comment by jdrch** [comment]
I'll look into it on my Windows 11 laptop. At the last update I was having the same issue with native Windows apps but it seems lately mostly Android Messages and WhatsApp are affected. Thanks for the continued effort on this!
